apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-converter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: temperature-converter
  template:
    metadata:
      labels:
        app: temperature-converter
    spec:
      containers:
        - name: conversion
          image: fernandorochaworld/temperature-converter:v0.2.0
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: temperature-converter
spec:
  selector:
    app: temperature-converter
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
